# theme: minima
remote_theme: jekyll/minima
minima:
  skin: dark # classic # solarized # solarized-dark # dark

baseurl: /today # the subpath of your site, e.g. /blog
# url: https://ppa4ipa.com # the base hostname & protocol for your site
# domain: ppa4ipa.com
permalink: /:title
# email: no@email.com
author: Новороссийская Церковь ЕХБ # Краснодарский край, г. Новороссийск, ул. Плавневая д. 1
# twitter_username: me
# github_username:  me

title: Чтение Библии на сегодня
longtitle: Новороссийская Церковь Евангельских Христиан-Баптистов

description: «Исследуйте Писания, ибо вы думаете чрез них иметь жизнь вечную; а они свидетельствуют о Мне.» (Иоанна 5:39)

# header_pages:
#   - index.md
#   - contacts.md

show_excerpts: false

sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: "/img/card.png"
      layout: day
  -
    scope:
      path: "img"
    values:
      image: true
plugins:
  - jekyll-sitemap

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
